This is makeindex, version 2.16 [MiKTeX 24.1].
Scanning style file ./dissertation.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file dissertation.acn....done (5 entries accepted, 0 rejected).
Sorting entries....done (12 comparisons).
Generating output file dissertation.acr....done (9 lines written, 0 warnings).
Output written in dissertation.acr.
Transcript written in dissertation.alg.
